Repository getgauge/gauge-java, pull requests merged in 2019-02, with the labels that each got.

#233 Fixing custom compile directory split, #231
  pom.xml
  src/main/java/com/thoughtworks/gauge/FileHelper.java
  src/main/java/com/thoughtworks/gauge/GaugeConstant.java
  src/main/java/com/thoughtworks/gauge/Util.java
  src/main/java/com/thoughtworks/gauge/connection/StubImplementationCodeProcessor.java
  src/main/java/com/thoughtworks/gauge/refactor/JavaRefactoring.java
  src/main/java/com/thoughtworks/gauge/refactor/RefactoringMethodVisitor.java
  src/test/java/com/thoughtworks/gauge/FileHelperTest.java
  src/test/java/com/thoughtworks/gauge/UtilTest.java
  src/test/java/com/thoughtworks/gauge/processor/CacheFileRequestProcessorTest.java
  src/test/java/com/thoughtworks/gauge/processor/StepPositionsRequestProcessorTest.java
  src/test/java/com/thoughtworks/gauge/scan/StaticScannerTest.java
Labels: cla-signed, ready

#239 Fixing package to scan
  src/main/java/com/thoughtworks/gauge/GaugeRuntime.java
  src/main/java/com/thoughtworks/gauge/connection/MessageDispatcher.java
  src/main/java/com/thoughtworks/gauge/processor/StepNameRequestProcessor.java
  src/main/java/com/thoughtworks/gauge/refactor/JavaRefactoring.java
  src/main/java/com/thoughtworks/gauge/registry/StepRegistry.java
  src/test/java/com/thoughtworks/gauge/processor/StepNameRequestProcessorTest.java
  src/test/java/com/thoughtworks/gauge/refactor/JavaRefactoringTest.java
Labels: cla-signed, ready

#238 concatenates annotation step text during static parsing.
  src/main/java/com/thoughtworks/gauge/scan/RegistryMethodVisitor.java
  src/test/java/com/thoughtworks/gauge/scan/StaticScannerTest.java
Labels: cla-signed, ready

#241 Custom classinitializer fix
  src/main/java/com/thoughtworks/gauge/GaugeRuntime.java
  src/main/java/com/thoughtworks/gauge/connection/MessageDispatcher.java
  src/main/java/com/thoughtworks/gauge/datastore/DataStoreInitializer.java
  src/main/java/com/thoughtworks/gauge/processor/KillProcessProcessor.java
  src/main/java/com/thoughtworks/gauge/processor/RefactorRequestProcessor.java
Labels: ready

#244 Update StepImpl.java
  src/test/resources/test/files/formatted/StepImpl.java
Labels: cla-signed, ready

#249 Update StepImpl.java
  src/test/resources/test/files/formatted/StepImpl.java
Labels: ready

#251 A method signature refactored to match with the actual test
  src/test/java/com/thoughtworks/gauge/refactor/JavaRefactoringTest.java
  src/test/resources/test/files/formatted/StepImpl.java
Labels: cla-signed, ready

#252 Added a test for step with common slash
  src/test/resources/test/files/formatted/StepImpl.java
Labels: cla-signed, ready for Development
