Repository getgauge/gauge-java, pull requests merged in 2020-03, with the labels that each got.

#376 Consider src/main/java and src/test/java as a default implementaion location
  src/main/java/com/thoughtworks/gauge/FileHelper.java
  src/main/java/com/thoughtworks/gauge/GaugeConstant.java
  src/test/java/com/thoughtworks/gauge/FileHelperTest.java
Labels: ReleaseCandidate, cla-signed

#387 Revert checkstyle and reflections upgrade
  pom.xml
Labels: cla-signed

#400 Upgrade checkstyle version
  checkstyle.xml
  pom.xml
Labels: cla-signed

#399 Upgrade to version 2 of github actions checkout
  .github/workflows/tests.yml
Labels: cla-signed

#393 Update java parser. #95
  pom.xml
  src/main/java/com/thoughtworks/gauge/connection/StubImplementationCodeProcessor.java
  src/main/java/com/thoughtworks/gauge/refactor/JavaParseWorker.java
  src/main/java/com/thoughtworks/gauge/refactor/JavaRefactoring.java
  src/main/java/com/thoughtworks/gauge/refactor/RefactoringMethodVisitor.java
  src/main/java/com/thoughtworks/gauge/scan/RegistryMethodVisitor.java
  src/main/java/com/thoughtworks/gauge/scan/StaticScanner.java
  src/test/java/com/thoughtworks/gauge/refactor/JavaRefactoringTest.java
Labels: cla-signed

#405 Honour JAVA_HOME and gauge_java_home. #378
  bin/launcher.ps1
  bin/launcher.sh
Labels: cla-signed

#406 Using class to calculate span if methods does not exists. #391
  src/main/java/com/thoughtworks/gauge/connection/StubImplementationCodeProcessor.java
  src/test/java/com/thoughtworks/gauge/processor/StubImplementationCodeProcessorTest.java
  src/test/resources/test/files/Empty.java
Labels: bug, cla-signed
