Repository getgauge/gauge-java, pull requests merged in 2020-10, with the labels that each got.

#507 #502 handle null case in method
  java.json
  pom.xml
  src/main/java/com/thoughtworks/gauge/processor/ExecuteStepProcessor.java
Labels: ReleaseCandidate, bug

#506 use NettyServerBuilder, bind to 127.0.0.1
  src/main/java/com/thoughtworks/gauge/GaugeConstant.java
  src/main/java/com/thoughtworks/gauge/command/StartCommand.java
Labels: ReleaseCandidate, bug

#515 Bump up versions for a release
  java.json
  pom.xml
Labels: ReleaseCandidate

#520 Adds a method to get datastore map
  java.json
  pom.xml
  src/main/java/com/thoughtworks/gauge/datastore/ScenarioDataStore.java
  src/main/java/com/thoughtworks/gauge/datastore/SpecDataStore.java
  src/main/java/com/thoughtworks/gauge/datastore/SuiteDataStore.java
Labels: ReleaseCandidate, feature
