Repository getgauge/gauge-java, pull requests merged in 2020-04, with the labels that each got.

#413 Use arguments file to avoid long classpaths. #402
  .github/workflows/tests.yml
  bin/launcher.ps1
  bin/launcher.sh
Labels: ReleaseCandidate, bug

#415 414 launcher fix
  bin/launcher.sh
  java.json
  pom.xml
Labels: ReleaseCandidate

#422 Get tmp dir using mktemp
  bin/launcher.sh
Labels: bug

#433 use singleThreadExecutor instead of custom executor
  src/main/java/com/thoughtworks/gauge/execution/ExecutorPool.java
  src/main/java/com/thoughtworks/gauge/execution/TaskExecutor.java
Labels: ReleaseCandidate, bug
